apply plugin: 'application'

group = 'org.comroid'
version = '1'
mainClassName = 'org.comroid.eventserverstarter.Program'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':japi')
    implementation 'net.dv8tion:JDA:+'
    implementation 'com.fasterxml.jackson.core:jackson-databind:+'

    testImplementation platform('org.junit:junit-bom:+')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // lombok
    implementation 'org.projectlombok:lombok:+'
    annotationProcessor 'org.projectlombok:lombok:+'
}

test {
    useJUnitPlatform()
}
