apply plugin: 'application'

group = 'org.comroid'
version = '1'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':japi')
    implementation 'net.dv8tion:JDA:5.+'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.+'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}